### ISSUE TITLE
[BUG] The type initializer for 'ProjBobcat.Platforms.Windows.SystemInfoHelper' threw an exception.

### ISSUE THREAD

**Issue by TaigoStudio** [Corona-Studio/ProjBobcat#156]
**Describe the bug**
When trying to get the version, an error occurs on some PCs. How can this be fixed?

**Desktop (please complete the following information):**
 - OS: Windows 11

[ERROR 30.06.2024 11:15:24]: System.TypeInitializationException: The type initializer for 'ProjBobcat.Platforms.Windows.SystemInfoHelper' threw an exception.
 ---> System.ComponentModel.Win32Exception (1058): The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.
   at System.Diagnostics.PerformanceMonitor.GetData(String item, Boolean usePool)
   at System.Diagnostics.PerformanceCounterLib.GetPerformanceData(String item, Boolean usePool)
   at System.Diagnostics.PerformanceCounterLib.get_CategoryTable()
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String category, String counter, Boolean& categoryExists)
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
   at System.Diagnostics.PerformanceCounter.InitializeImpl()
   at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName, Boolean readOnly)
   at ProjBobcat.Platforms.Windows.SystemInfoHelper..cctor()
   --- End of inner exception stack trace ---
   at ProjBobcat.Platforms.Windows.SystemInfoHelper.GetWindowsMajorVersion()
   at ProjBobcat.Class.Model.OperatingSystemRules.IsAllow()
   at ProjBobcat.Class.Helper.RulesHelper.CheckAllow(IEnumerable`1 rules)
   at ProjBobcat.DefaultComponent.Launch.DefaultVersionLocator.ParseJvmArguments(JsonElement[] arguments)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ProjBobcat.DefaultComponent.Launch.DefaultVersionLocator.ToVersion(String id)
   at ProjBobcat.DefaultComponent.Launch.DefaultVersionLocator.GetGame(String id)

**Comment by laolarou726** [comment]
Just pushed a fix to master

**Comment by TaigoStudio** [comment]
[ERROR 07.07.2024 15:46:14]: System.TypeInitializationException: The type initializer for 'ProjBobcat.Platforms.Windows.SystemInfoHelper' threw an exception.
 ---> System.ComponentModel.Win32Exception (1058): The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.
   at System.Diagnostics.PerformanceMonitor.GetData(String item, Boolean usePool)
   at System.Diagnostics.PerformanceCounterLib.GetPerformanceData(String item, Boolean usePool)
   at System.Diagnostics.PerformanceCounterLib.get_CategoryTable()
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String category, String counter, Boolean& categoryExists)
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
   at System.Diagnostics.PerformanceCounter.InitializeImpl()
   at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName, Boolean readOnly)
   at ProjBobcat.Platforms.Windows.SystemInfoHelper..cctor()
   --- End of inner exception stack trace ---
   at ProjBobcat.Platforms.Windows.SystemInfoHelper.GetWindowsMajorVersion()
   at ProjBobcat.Class.Model.OperatingSystemRules.IsAllow()
   at ProjBobcat.Class.Helper.RulesHelper.CheckAllow(IEnumerable`1 rules)
   at ProjBobcat.DefaultComponent.Launch.DefaultVersionLocator.ParseJvmArguments(JsonElement[] arguments)+MoveNext()
   at ProjBobcat.DefaultComponent.Launch.DefaultLaunchArgumentParser.ParseJvmArguments()+MoveNext()
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at ProjBobcat.DefaultComponent.Launch.DefaultLaunchArgumentParser.GenerateLaunchArguments()
   at ProjBobcat.DefaultComponent.Launch.GameCore.DefaultGameCore.LaunchTaskAsync(LaunchSettings settings) Exception occurred when launching game. None
[
