### ISSUE TITLE
[BUG] The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.

### ISSUE THREAD

**Issue by TaigoStudio** [Corona-Studio/ProjBobcat#159]
- OS: ReviOS (Windows 11)

[ERROR 07.07.2024 15:46:14]: System.TypeInitializationException: The type initializer for 'ProjBobcat.Platforms.Windows.SystemInfoHelper' threw an exception.
---> System.ComponentModel.Win32Exception (1058): The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.
at System.Diagnostics.PerformanceMonitor.GetData(String item, Boolean usePool)
at System.Diagnostics.PerformanceCounterLib.GetPerformanceData(String item, Boolean usePool)
at System.Diagnostics.PerformanceCounterLib.get_CategoryTable()
at System.Diagnostics.PerformanceCounterLib.CounterExists(String category, String counter, Boolean& categoryExists)
at System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
at System.Diagnostics.PerformanceCounter.InitializeImpl()
at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName, Boolean readOnly)
at ProjBobcat.Platforms.Windows.SystemInfoHelper..cctor()
--- End of inner exception stack trace ---
at ProjBobcat.Platforms.Windows.SystemInfoHelper.GetWindowsMajorVersion()
at ProjBobcat.Class.Model.OperatingSystemRules.IsAllow()
at ProjBobcat.Class.Helper.RulesHelper.CheckAllow(IEnumerable1 rules) at ProjBobcat.DefaultComponent.Launch.DefaultVersionLocator.ParseJvmArguments(JsonElement[] arguments)+MoveNext() at ProjBobcat.DefaultComponent.Launch.DefaultLaunchArgumentParser.ParseJvmArguments()+MoveNext() at System.Collections.Generic.List1.AddRange(IEnumerable`1 collection)
at ProjBobcat.DefaultComponent.Launch.DefaultLaunchArgumentParser.GenerateLaunchArguments()
at ProjBobcat.DefaultComponent.Launch.GameCore.DefaultGameCore.LaunchTaskAsync(LaunchSettings settings) Exception occurred when launching game. None

**Comment by laolarou726** [comment]
Are you using the latest `master` branch?

**Comment by TaigoStudio** [comment]
Strangely, it looks like I used the code but from the last commit.

**Comment by laolarou726** [comment]
> Strangely, it looks like I used the code but from the last commit.

So the issue is resolved?

**Comment by TaigoStudio** [comment]
I sent the update to the person whose startup is not working. I'm waiting for an answer from him
