### ISSUE TITLE
[BUG] Some files don't have time to load

### ISSUE THREAD

**Issue by TaigoStudio** [Corona-Studio/ProjBobcat#162]
On some computers, files that are large enough may not be downloaded in time. How can I edit the Timeout time or try to reload libraries that failed to load after downloading?
![image](https://github.com/user-attachments/assets/80df7b5e-84b3-442b-916a-d1faead7951c)

Logs:
[ERROR 12.07.2024 13:05:53]: https://resources.download.minecraft.net/5b/5b3ae419f7f7648568f0b5303594078aea12f598: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at ProjBobcat.Class.Helper.DownloadHelper.MultiPartDownloadTaskAsync(DownloadFile downloadFile, DownloadSettings downloadSettings)
[ERROR 12.07.2024 13:05:58]: https://resources.download.minecraft.net/35/352bc5b46e08effbb8d92298b601e688cc36c4de: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at ProjBobcat.Class.Helper.DownloadHelper.MultiPartDownloadTaskAsync(DownloadFile downloadFile, DownloadSettings downloadSettings)
[ERROR 12.07.2024 13:06:09]: https://resources.download.minecraft.net/5b/5b3ae419f7f7648568f0b5303594078aea12f598: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at ProjBobcat.Class.Helper.DownloadHelper.MultiPartDownloadTaskAsync(DownloadFile downloadFile, DownloadSettings downloadSettings)
[ERROR 12.07.2024 13:06:14]: https://resources.download.minecraft.net/35/352bc5b46e08effbb8d92298b601e688cc36c4de: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at ProjBobcat.Class.Helper.DownloadHelper.MultiPartDownloadTaskAsync(DownloadFile downloadFile, DownloadSettings downloadSettings)
[ERROR 12.07.2024 13:06:34]: https://resources.download.minecraft.net/86/868c7a7c4d9358d631fa2f9abfc6bbf05d88292d: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at ProjBobcat.Class.Helper.DownloadHelper.MultiPartDownloadTaskAsync(DownloadFile downloadFile, DownloadSettings downloadSettings)
[ERROR 12.07.2024 13:06:34]: https://resources.download.minecraft.net/5b/5b3ae419f7f7648568f0b5303594078aea12f598: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at ProjBobcat.Class.Helper.DownloadHelper.MultiPartDownloadTaskAsync(DownloadFile downloadFile, DownloadSettings downloadSettings)

**Comment by laolarou726** [comment]
you can set retry and timeout when you performing download

**Comment by TaigoStudio** [comment]
Yes, I used outdated documentation, Found a solution in [ProjBobcat.Samples](https://github.com/Corona-Studio/ProjBobcat.Samples/tree/main).
